plugins {
    id 'java'
    id "net.codecrete.windows-api" version "0.8.5"
}

group = 'org.example'
version = '1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

generateWindowsApi {
    functions = [
            "CoTaskMemFree",
            "FormatMessageW",
            "GetModuleHandleW",
            "GetVolumePathNameW",
            "LocalFree",
            "SHGetKnownFolderPath",
    ]
    constants = [
            "FOLDERID_CommonPrograms",
            "FOLDERID_Desktop",
            "FOLDERID_Programs",
            "FOLDERID_PublicDesktop",
            "S_OK",
    ]
}
