<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.example</groupId>
  <artifactId>taskbar</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>taskbar</name>
  <url>http://maven.apache.org</url>

  <properties>
    <maven.compiler.source>25</maven.compiler.source>
    <maven.compiler.target>25</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <build>
    <plugins>
      <plugin>
        <groupId>net.codecrete.windows-api</groupId>
        <artifactId>windowsapi-maven-plugin</artifactId>
        <version>0.8.6</version>
        <executions>
          <execution>
            <goals>
              <goal>windows-api</goal>
            </goals>
            <configuration>
              <comInterfaces>
                <comInterface>ITaskbarList3</comInterface>
              </comInterfaces>
              <functions>
                <function>CoCreateInstance</function>
                <function>CoInitializeEx</function>
                <function>FindWindowW</function>
                <function>FormatMessageW</function>
                <function>GetModuleHandleW</function>
                <function>LocalFree</function>
              </functions>
              <constants>
                <constant>S_OK</constant>
                <constant>TaskbarList</constant>
              </constants>
              <downcallTracing>false</downcallTracing>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>
